# ---------------------------------------------------------------------------
# S3 Bucket
# ---------------------------------------------------------------------------
resource "aws_s3_bucket" "uploads" {
  bucket = var.bucket_name
}

# ---------------------------------------------------------------------------
# Lambda Deployment Packages (auto-generated by Terraform)
# ---------------------------------------------------------------------------
data "archive_file" "function1" {
  type        = "zip"
  source_file = "${path.module}/../lambda/function1_s3_handler/lambda_function.py"
  output_path = "${path.module}/dist/function1.zip"
}

data "archive_file" "function2" {
  type        = "zip"
  source_file = "${path.module}/../lambda/function2_formatter/lambda_function.py"
  output_path = "${path.module}/dist/function2.zip"
}

# ---------------------------------------------------------------------------
# Lambda Function 1: S3 Event Handler
# ---------------------------------------------------------------------------
resource "aws_lambda_function" "function1" {
  function_name = var.lambda_1_name
  role          = aws_iam_role.lambda_exec.arn
  handler       = "lambda_function.lambda_handler"
  runtime       = "python3.11"
  filename      = data.archive_file.function1.output_path
  source_code_hash = data.archive_file.function1.output_base64sha256

  environment {
    variables = {
      FUNCTION_2_NAME = var.lambda_2_name
      # LocalStack endpoint for cross-Lambda invocation inside Docker
      AWS_ENDPOINT_URL = "http://host.docker.internal:4566"
    }
  }

  timeout     = 30
  memory_size = 128

  depends_on = [aws_iam_role_policy_attachment.lambda_basic]
}

# ---------------------------------------------------------------------------
# Lambda Function 2: Response Formatter
# ---------------------------------------------------------------------------
resource "aws_lambda_function" "function2" {
  function_name = var.lambda_2_name
  role          = aws_iam_role.lambda_exec.arn
  handler       = "lambda_function.lambda_handler"
  runtime       = "python3.11"
  filename      = data.archive_file.function2.output_path
  source_code_hash = data.archive_file.function2.output_base64sha256

  timeout     = 30
  memory_size = 128

  depends_on = [aws_iam_role_policy_attachment.lambda_basic]
}

# ---------------------------------------------------------------------------
# Lambda Permission: Allow S3 to invoke Function 1
# ---------------------------------------------------------------------------
resource "aws_lambda_permission" "allow_s3" {
  statement_id  = "AllowS3Invoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.function1.function_name
  principal     = "s3.amazonaws.com"
  source_arn    = aws_s3_bucket.uploads.arn
}

# ---------------------------------------------------------------------------
# S3 Event Notification: Trigger Function 1 on ObjectCreated
# ---------------------------------------------------------------------------
resource "aws_s3_bucket_notification" "bucket_notification" {
  bucket = aws_s3_bucket.uploads.id

  lambda_function {
    lambda_function_arn = aws_lambda_function.function1.arn
    events              = ["s3:ObjectCreated:*"]
  }

  depends_on = [aws_lambda_permission.allow_s3]
}