apiVersion: v1
kind: ResourceQuota
metadata:
  name: three-tier-quota
  namespace: three-tier
spec:
  hard:
    requests.cpu: "1000m"
    requests.memory: "1Gi"
    limits.cpu: "2000m"
    limits.memory: "2Gi"
    pods: "15"
    persistentvolumeclaims: "5"
    services: "5"