apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: production
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/devopsdb"
  SPRING_DATASOURCE_USERNAME: "devops"